name: heroku-mezamaci

on:
  schedule:
    - cron: '0,20,40 0-15 * * *'

jobs:
  mezamashi:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up heroku app
        env:
          APP_URL: ${{ secrets.APP_URL }}
        run: curl --head $APP_URL
      - name: Print current time (JST)
        env:
          TZ: "Asia/Tokyo"
        run: date
