name: heroku-mezamaci

on:
  schedule:
    - cron: '0,20,40 0-15 * * *'

jobs:
  mezamashi:
    runs-on: ubuntu-latest
    steps:
      - name: wake up heroku app
        run: curl --head https://it-benkyoukai-meishi.herokuapp.com/
      - name: print current time (JST)
        env:
          TZ: "Asia/Tokyo"
        run: date
