name: scheduled!

on:
  push:
    branches:
      - master

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: print current time (JST)
        env:
          TZ: "Asia/Tokyo"
        run: date
