name: scheduled!

on:
  push:
    branches:
      - master

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time (JST)
        env:
          TZ: "Asia/Tokyo"
        run: date
      - name: Print app url
        env:
          APP_URL: ${{ secrets.APP_URL }}
        run: echo $APP_URL
